INSERT INTO "public"."baseagrodata_news" ("id", "title", "summary", "content", "category", "image_url", "date", "views", "created_at", "site_id", "slug", "visible_in_baseagrodata") VALUES ('0595212b-519c-4b90-a1af-e76c579729b0', 'Canavial da Manhiça necessita de 1000 milhões de meticais para reposição', '
As intensas chuvas que têm se verificado, nos últimos dias, inundaram cerca de 10 000 hectares de plantação de cana-de-açúcar que neces...', '<!-- wp:paragraph -->
<p>As intensas chuvas que têm se verificado, nos últimos dias, inundaram cerca de 10 000 hectares de plantação de cana-de-açúcar que necessitam de 1000 milhões de meticais para s...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-30 21:37:15+00', 426, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'canavial-da-manhica-necessita-de-1000-milhoes-de-meticais-para-reposicao', true), ('0d9fecf5-40f0-4004-ba75-b7068ad37a7d', 'Lançada II edição do concurso de boas práticas de Segurança e Saúde no Trabalho', '
Foi lançado ontem, segunda-feira (24), o II Concurso de Boas Práticas de Segurança e Saúde no Trabalho pelo <a href="https://www.facebo...', '<!-- wp:paragraph -->
<p>Foi lançado ontem, segunda-feira (24), o II Concurso de Boas Práticas de Segurança e Saúde no Trabalho pelo <a href="https://www.facebook.com/ministeriodotrabalhoesegurancasoc...', 'Meios de vida', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2022-10-25 19:07:28+00', 265, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'ministerio-do-trabalho-e-seguranca-social', true), ('126348c5-0bf4-4a57-ab79-b61ad4bf8d09', 'Agricultores de Marracuene e Bobole trocam experiências', 'No âmbito da garantia da produção, produtividade e competitividade entre os produtores a nível do mercado, a Helpcod em parceria com os Serviços Distritais das Actividades Económicas (SDAE) de Marracuene, promoveu, na semana finda, um intercâmbio visando troca de experiência entre os produtores de Marracuene e Bobole, na província de Maputo.', '<!-- wp:paragraph -->
<p>No âmbito da garantia da produção, produtividade e competitividade entre os produtores a nível do mercado, a Helpcod em parceria com os Serviços Distritais das Actividades Eco...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-06-11 06:32:27+00', 219, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'agricultores-de-marracuene-e-bobole-trocam-experiencias', true), ('12ab9b68-e59d-4fd4-8c1e-7f594c60e1fc', '1º SIMPÓSIO DA INVESTIGAÇÃO AGRÁRIA: Governo vai investir 3 bilhões no sector agrícola', '
O Governo vai investir, nos próximos dois anos, 3 bilhões de meticais na investigação agrária em Moçambique, com vista a produzir soluç...', '<!-- wp:paragraph -->
<p>O Governo vai investir, nos próximos dois anos, 3 bilhões de meticais na investigação agrária em Moçambique, com vista a produzir soluções tecnológicas para erradicar a pobrez...', 'Sector agrario', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2022-08-30 19:02:22+00', 490, '2026-04-24 11:23:51.241139+00', 'baseagrodata', '1-simposio-da-investigacao-agraria-governo-vai-investir-3-bilhoes-no-sector-agricola', true), ('14dd4cde-109f-4a19-8fbc-a1aa38ae71e0', 'Segurança alimentar: Crise global pode persistir', '
Organizações internacionais reiteram apelo conjunto a uma acção rápida em matéria de segurança alimentar e nutricional
<!-- /wp:par...', '<!-- wp:paragraph -->
<p>Organizações internacionais reiteram apelo conjunto a uma acção rápida em matéria de segurança alimentar e nutricional</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Um ...', 'Seguranca-alimentar', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-23 21:32:38+00', 476, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'seguranca-alimentar-crise-global-pode-persistir', true), ('15551617-55b3-4927-a846-cd7d0ce6d75c', 'ES KaTembe rumo á melhoria de qualidade de ensino', '
O conselho de Escola da Escola Secundária de KaTembe, no distrito municipal KaTembe, na cidade de Maputo está empenhado no melhoramento...', '<!-- wp:paragraph -->
<p>O conselho de Escola da Escola Secundária de KaTembe, no distrito municipal KaTembe, na cidade de Maputo está empenhado no melhoramento e apetrechamento daquela unidade de ens...', 'Comunidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-06-09 15:38:09+00', 544, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'es-katembe-rumo-a-melhoria-de-qualidade-de-ensino', true), ('17e67521-4d29-4e8b-bf7c-51e6b701cb2d', 'Bielorrússia pretende investir no sector agrário em Moçambique', '
O presidente Bielorusso, Aleksandr Lukashenko, afirmou, na terça-feira (28), em Harare - capital de Zimbabwe que tenciona estreitar rel...', '<!-- wp:paragraph -->
<p>O presidente Bielorusso, Aleksandr Lukashenko, afirmou, na terça-feira (28), em Harare - capital de Zimbabwe que tenciona estreitar relações de cooperação no sector agrário co...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-01 08:49:16+00', 295, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'bielorrussia-pretende-investir-no-sector-agrario-em-mocambique', true), ('1ace35d9-c504-449e-b60c-915f7460b770', 'Para acesso ao mercado internacional: Frutisul capacita seus membros', '
A&nbsp;Frutisul, uma associação moçambicana de fruticultores, capacita seus membros em ...', '<!-- wp:paragraph -->
<p>A&nbsp;<a href="https://www.frutisul.com.br/site/">Frutisul</a>, uma associação moçambicana de fruticultores, capacita seus membros em matéria de acesso ao mercado internacion...', 'Fruticultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2022-07-29 19:45:47+00', 157, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'para-acesso-ao-mercado-internacional-frutisul-capacita-seus-membros', true), ('1c00c188-4e2f-4d9c-9502-ad582efacbd1', 'Altas taxas da portagem boicotam desenvolvimento socioeconómico de KaTembe', '
Depois da inauguração da Ponte Maputo/KaTembe, as expectativas sobre o desenvolvimento do distrito foram maiores, mas o elevado custo d...', '<!-- wp:paragraph -->
<p>Depois da inauguração da Ponte Maputo/KaTembe, as expectativas sobre o desenvolvimento do distrito foram maiores, mas o elevado custo da viagem boicotou o sonho de quem espera...', 'Comunidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2020-11-16 15:50:33+00', 472, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'custo-de-travessia-maputo-katembe-boicota-desenvolvimento-economico-do-distrito', true), ('1ee294ce-9f66-42ab-b5cb-6741c18effab', 'Wrap de vegetais com polpa de mafpilwa', '
INGREDIENTES




2 uni. de folha de Wrap</e...', '<!-- wp:paragraph -->
<p><strong>INGREDIENTES</strong></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>2 uni. de folha de <em>Wrap</em></li>
<!-- /wp:list-item -->

<!-- wp:...', 'Receitas', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-02-02 11:04:45+00', 50, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'wrap-de-vegetais-com-polpa-de-mafpilwa', true), ('21bb4b34-d11a-4650-8030-6952eafe8c65', 'No país: USAID lança janela de financiamento agroindustrial', '
A Agência Americana de Desenvolvimento Internacional (USAID), através do projecto FTF Premier, lançou, a 06 de Abril de 2023, ...', '<!-- wp:paragraph -->
<p>A Agência Americana de Desenvolvimento Internacional (USAID), através do projecto <em>FTF Premier</em>, lançou, a 06 de Abril de 2023, uma janela de subvenções para o financia...', 'Oportunidades', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-04-18 19:37:54+00', 101, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'no-pais-usaid-lanca-janela-de-financiamento-agroindustrial', true), ('21bc89dd-6eb7-4a26-97e3-f6316c9ee008', 'Na Nigéria: Crianças sem acesso à educação', '
Dezenas de milhares de crianças estão sem acesso à educação na Nigéria, devido aos ataques de insurgentes e outros grupos armados. Segu...', '<!-- wp:paragraph -->
<p>Dezenas de milhares de crianças estão sem acesso à educação na Nigéria, devido aos ataques de insurgentes e outros grupos armados. Segundo a Amnistia Internacional, esta situa...', 'Sem categoria', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-07-07 17:59:46+00', 437, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'na-nigeria-criancas-sem-acesso-a-educacao', true), ('2356ff55-eb5d-46a6-bae9-a0afd37c4070', 'Moradores sentem-se seguros nas zonas baixas', '
“Não temos nada a temer aqui”



Os Moradores do bairro zona verde,...', '<!-- wp:list -->
<ul><li><strong>“Não temos nada a temer aqui”</strong></li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>Os Moradores do bairro zona verde, próximo ao cruzamento do bairro Malhazi...', 'Comunidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-06-06 21:05:25+00', 134, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'moradores-sentem-se-seguros-nas-zonas-baixas', true), ('2368b0c2-f295-4b2e-ae22-ada92f846d46', 'Tomate – o “fruto do diabo”', '
O tomate foi uma das novidades trazidas da América na época dos Descobrimentos. Originário do México, onde era chamado pelos povos loca...', '<!-- wp:paragraph -->
<p>O tomate foi uma das novidades trazidas da América na época dos Descobrimentos. Originário do México, onde era chamado pelos povos locais de tomatl, o tomate chegou à Europa a...', 'Curiosidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-06-06 07:15:26+00', 103, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'tomate-o-fruto-do-diabo', true), ('26242aa4-6266-412c-8dd8-54fc78a44739', 'Produção de GPL vai reforçar energia limpa e combater desmatamento em Moçambique', 'Moçambique poderá iniciar a produção nacional de gás de cozinha até ao início de 2026, a partir de Inhassoro, na província de Inhambane. A iniciativa integra...', '<p>Moçambique poderá iniciar a produção nacional de gás de cozinha até ao início de 2026, a partir de Inhassoro, na província de Inhambane. A iniciativa integra o Projecto Integrado de Gás de Temane e...', 'Agricultura', 'https://ppgmtxzuaxqshipnvebl.supabase.co/storage/v1/object/public/news-images/producao-de-gpl-vai-reforcar-energia-limpa-e-combater-desmatamento-em-mocambique-1776978016191.jpg', '2025-07-15 15:22:37+00', 260, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'producao-de-gpl-vai-reforcar-energia-limpa-e-combater-desmatamento-em-mocambique', true), ('27ca8b52-84ac-46c4-8d5b-11552d755812', 'Com apoio da AGRA, Governo moçambicano aposta na agricultura jovem como pilar da diversificação económica', '
A agricultura volta a ocupar um papel central na transformação económica de Moçambique, com o Governo e a AGRA – Aliança para a Revoluç...', '<!-- wp:paragraph -->
<p>A agricultura volta a ocupar um papel central na transformação económica de Moçambique, com o Governo e a AGRA – Aliança para a Revolução Verde em África – a avançarem com uma...', 'Agricultura', '<![CDATA[https://entrecampos.co.mz/wp-content/uploads/2025/06/AGRA-Impulsiona-Inclusao-Jovem-na-Agricultura-com-Apoio-ao-Governo.jpg]]>', '2025-06-26 10:24:53+00', 408, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'com-apoio-da-agra-governo-mocambicano-aposta-na-agricultura-jovem-como-pilar-da-diversificacao-economica', true), ('29d8208e-3494-40de-a1f2-4d5c9b2d7d72', 'Dia de Campo: Instituto de Investigação Agrária apresenta soluções contra mosca da fruta', '
O Instituto de Investigação Agrária de Moçambique (IIAM) apresentou hoje, 14 de Outubro de 2022, soluções para o maneio da mosca da fru...', '<!-- wp:paragraph -->
<p>O Instituto de Investigação Agrária de Moçambique (IIAM) apresentou hoje, 14 de Outubro de 2022, soluções para o maneio da mosca da fruta no distrito de Boane, província de Ma...', 'Fruticultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2022-10-14 23:38:27+00', 269, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'dia-de-campo-iiam-apresenta-solucoes-contra-a-mosca-da-fruta', true), ('2b3a6f7e-ab7d-495a-b6f4-eda817b30918', 'Há um lugar no mundo onde a batata reno é homenageada', '
Os moradores do condado de Clark, em Dakota do Sul (um dos 50 Estados dos Estados Unidos da América), dedicam um dia todos os anos para...', '<!-- wp:paragraph -->
<p>Os moradores do condado de Clark, em Dakota do Sul (um dos 50 Estados dos Estados Unidos da América), dedicam um dia todos os anos para homenagear a sua mais importante fonte ...', 'Curiosidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-06-06 07:24:44+00', 464, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'ha-um-lugar-no-mundo-onde-a-batata-reno-e-homenageada', true), ('2cc3e735-3ce3-4f31-9114-a818d8c65ea9', 'Cotas pagas à ACRIVERDE não beneficiam associados – Alexandre Ouana', '
As cotas anuais pagas à Associação de Criadores e Agricultores da Zona Verde (ACRIVERDE) não beneficiam diretamente os associados, diz ...', '<!-- wp:paragraph -->
<p>As cotas anuais pagas à Associação de Criadores e Agricultores da Zona Verde (ACRIVERDE) não beneficiam diretamente os associados, diz o presidente da agremiação Alexandre Oua...', 'Sector agrario', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-23 21:03:09+00', 184, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'cotas-pagas-a-acriverde-nao-beneficiam-associados-alexandre-ouana', true), ('2d8727f7-efed-4a36-aa4e-4532975ed0ca', 'Moçambique recebe US$ 25 milhões destinados à financiamento  de projectos sobre meio ambiente', '
A Directora Interina de Políticas, Parcerias e Operações do Global Environment Facility (GEF), Paola Ridolfi, confirmou, no encontro qu...', '<!-- wp:paragraph -->
<p>A Directora Interina de Políticas, Parcerias e Operações do Global Environment Facility (GEF), Paola Ridolfi, confirmou, no encontro que decorre entre 20 e 23 de Março, em Map...', 'Ambiente', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-23 21:26:13+00', 545, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'mocambique-recebe-us-25-milhoes-destinados-a-financiamento-de-projectos-sobre-meio-ambiente', true), ('30b4f43f-9b78-4e72-b95f-12bbfd933bda', 'Moçamboique e Itália apostam 160 milhões de euros para inovação agrária', 'Moçambique e Itália inauguraram uma nova fase da sua cooperação no agro-negócio, com a disponibilização de 160 milhões de euros destinados à modernização da ...', '<p>Moçambique e Itália inauguraram uma nova fase da sua cooperação no agro-negócio, com a disponibilização de 160 milhões de euros destinados à modernização da produção agrícola, dinamização de cadeia...', 'Agricultura', 'https://ppgmtxzuaxqshipnvebl.supabase.co/storage/v1/object/public/news-images/usaid-promove-workshop-sobre-digitalizacao-de-pmes-para-acesso-ao-mercado-internacional-1776978072202.jpg', '2025-09-20 21:44:54+00', 183, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'mocamboique-e-italia-apostam-160-milhoes-de-euros-para-inovacao-agro-industria-e-emprego-jovem', true), ('30daf0c3-a334-494f-9be7-1e5f1c61a1cc', 'Ciclone Fredy: BNI desembolsa 75 milhões de meticais para apoio às PME´s', '
O Banco Nacional de Investimento (BNI) vai desembolsar 75 milhões de meticais para o financiamento, especialmente, concebido para apoia...', '<!-- wp:paragraph -->
<p>O Banco Nacional de Investimento (BNI) vai desembolsar 75 milhões de meticais para o financiamento, especialmente, concebido para apoiar as pequenas e médias empresas que actu...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-04-14 16:24:41+00', 188, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'ciclone-fredy-bni-desembolsa-75-milhoes-de-meticais-para-apoio-as-pmes', true), ('398edff9-627c-416f-87da-86933515890d', 'Vision Sugar assume gestão das açucareiras de Xinavane e Mafambisse com foco no desenvolvimento rural', '
A Vision Sugar Holdings, consórcio africano com ambições regionais, anunciou a aquisição das açucareiras de Xinavane e Mafambisse, ante...', '<!-- wp:paragraph -->
<p>A Vision Sugar Holdings, consórcio africano com ambições regionais, anunciou a aquisição das açucareiras de Xinavane e Mafambisse, anteriormente geridas pela sul-africana Tong...', 'Comunidade', '<![CDATA[https://entrecampos.co.mz/wp-content/uploads/2025/06/Xinavane.jpg]]>', '2025-06-26 09:39:25+00', 88, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'vision-sugar-assume-gestao-das-acucareiras-de-xinavane-e-mafambisse-com-foco-no-desenvolvimento-rural', true), ('3a626708-45ad-4162-a764-5dc51e33f57f', 'Fraca gestão de Lixo: um problema com barba branca na Matola', '
A fraca gestão de lixo pelo Conselho Municipal da Cidade da Matola (CMCM) aflige comerciantes do mercado Khongolote, no Posto Administr...', '<!-- wp:paragraph -->
<p>A fraca gestão de lixo pelo Conselho Municipal da Cidade da Matola (CMCM) aflige comerciantes do mercado Khongolote, no Posto Administrativo do Infulene (PAI), província de Ma...', 'Comunidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-23 20:50:28+00', 396, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'fraca-gestao-de-lixo-um-problema-com-barba-branca-na-matola', true), ('3e2e8c62-3965-4330-a294-b7a795706bf7', 'USAID promove Workshop sobre digitalização de PMEs para acesso ao mercado internacional', '
No âmbito do Projecto de Desenvolvimento Econômico, Governação e Crescimento Empresarial (EDGE) da USAID, um Workshop foi agendado para...', '<!-- wp:paragraph -->
<p>No âmbito do Projecto de Desenvolvimento Econômico, Governação e Crescimento Empresarial (EDGE) da USAID, um Workshop foi agendado para terça-feira, 30 de Abril de 2024, com o...', 'Agro-negocio', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2024-04-24 08:48:40+00', 477, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'usaid-promove-workshop-sobre-digitalizacao-de-pmes-para-acesso-ao-mercado-internacional', true), ('43d0b76c-a4b6-428b-99af-8d6e223a0b56', 'Gutsamba realiza feira de degustação de gastronomia baseada em frutas silvestres', '
A Gutsamba - palavra em lingua tsonga que significa sabores realizou, no dia 20 de Maio do ano em curso, sábado último, uma feira gastr...', '<!-- wp:paragraph -->
<p>A Gutsamba - palavra em lingua tsonga que significa sabores realizou, no dia 20 de Maio do ano em curso, sábado último, uma feira gastronómica alusiva à degustação de alimento...', 'Agro-negocio', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-05-21 16:15:49+00', 540, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'agro-servicos-realiza-feira-de-degustacao-de-gastronomia-baseada-em-frutas-nativas-desvalorizadas', true), ('44cf9cb9-29b2-44d3-891a-be584d4e36c4', 'SADC Aposta na Industrialização e Energia Limpa', '
O Presidente da República, Daniel Chapo, participa em Antananarivo na 45.ª Cimeira da SADC, encontro dedicado a estratégias para aceler...', '<!-- wp:paragraph -->
<p>O Presidente da República, Daniel Chapo, participa em Antananarivo na 45.ª Cimeira da SADC, encontro dedicado a estratégias para acelerar a industrialização, transformar a agr...', 'Agricultura', '<![CDATA[https://entrecampos.co.mz/wp-content/uploads/2025/08/Industrializacao-Agricultura.jpg]]>', '2025-08-18 13:29:33+00', 153, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'sadc-aposta-na-industrializacao-e-energia-limpa', true), ('48f3faad-8f35-4fb2-8a9a-287b22de563a', 'Ressano Garcia: fronteira entre a vida e a morte', '
O Posto Administrativo de Ressano Garcia, no Distrito da Moamba, Província de Maputo, tem sido, nos últimos dias, palco de vários crime...', '<!-- wp:paragraph -->
<p>O Posto Administrativo de Ressano Garcia, no Distrito da Moamba, Província de Maputo, tem sido, nos últimos dias, palco de vários crimes protagonizados por indivíduos desconhe...', 'Comunidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-06-06 07:28:28+00', 456, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'tomate-o-fruto-do-diabo-2', true), ('525bef96-1759-4cd1-b10d-3d607ff71c6a', 'Alocados 600 milhões de meticais para agro-pecuário', '




Moçambique vai beneficiar de cerca de 600 milhões de meticais para o setor agro-p...', '<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Moçambique vai beneficiar de cerca de 600 milhões de meticais para o setor agro-pecuário, com vista ao melhoramento da ge...', 'Agro-pecuaria', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-04-26 20:29:52+00', 95, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'alocados-600-000-milhoes-de-meticais-para-o-sector-agropecuario', true), ('53e95d7a-fd21-4545-8c4c-dfd41f0fba56', 'Em Marracuene: Venda informal de peixe na origem do fracasso do comercio formal', '
A falta de fiscalização da venda informal de mariscos prejudica o comércio legal de peixe, na vila do distrito de Marracuene - provínci...', '<!-- wp:paragraph -->
<p>A falta de fiscalização da venda informal de mariscos prejudica o comércio legal de peixe, na vila do distrito de Marracuene - província de Maputo.</p>
<!-- /wp:paragraph -->
...', 'Agro-negocio', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-04-11 14:22:01+00', 473, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'em-marracuene-venda-informal-de-peixe-na-origem-do-fracasso-do-comercio-formal', true), ('5b7e3ce4-11a9-4dfc-8163-a64995e45a32', 'Alusivo ao dia Mundial da Mulher Rural: UNAC promove feira agrícola', '
A UNAC – União Nacional de Camponeses realizou, na manhã de hoje (15 de outubro de 2021), uma cerimónia de celebração do dia Internacio...', '<!-- wp:paragraph -->
<p>A UNAC – União Nacional de Camponeses realizou, na manhã de hoje (15 de outubro de 2021), uma cerimónia de celebração do dia Internacional da Mulher Rural, no distrito de Marr...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-10-15 19:43:07+00', 233, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'alusivo-ao-dia-mundial-da-mulher-rural-unac-promove-feira-agricola-e-gastronomica', true), ('5d4c7041-10ce-4272-afdc-3e0e20def0c6', 'MADER participa da 47ª edição do congresso internacional de apicultura', '
O Ministério de Agricultura e Desenvolvimento Rural – MADER participou da 47ª edição do Congresso Internacional de Apicultura que teve ...', '<!-- wp:paragraph -->
<p>O Ministério de Agricultura e Desenvolvimento Rural – MADER participou da 47ª edição do Congresso Internacional de Apicultura que teve lugar nos dias 24 e 28 de Agosto de corr...', 'Fruticultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2022-08-29 06:41:32+00', 265, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'mader-participa-da-47a-edicao-do-congresso-internacional-de-apicultura', true), ('600998b3-a778-45af-8be8-b4465fd8a10a', 'Transformação agrária: FIDA reforça apoio à agricultura inclusiva em Moçambique', '
O Fundo Internacional de Desenvolvimento Agrícola (FIDA) apelou ao Governo moçambicano para promover uma agricultura voltada para a cri...', '<!-- wp:paragraph -->
<p>O Fundo Internacional de Desenvolvimento Agrícola (FIDA) apelou ao Governo moçambicano para promover uma agricultura voltada para a criação de valor económico e geração de emp...', 'Agricultura', '<![CDATA[https://entrecampos.co.mz/wp-content/uploads/2025/07/FIDA-Defende-Agricultura-em-Mocambique-Centrada-na-Criacao-de-Valor-e-EmpregoII.jpg]]>', '2025-07-03 15:49:44+00', 68, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'transformacao-agraria-fida-reforca-apoio-a-agricultura-inclusiva-em-mocambique', true), ('671c7566-0753-4b6a-bacf-214006513918', 'Tênis, papel e pneu: conheça sete produtos feitos de milho', '
O milho para além de ser alimento precioso, dele obtém-se muitos produtos, desde a cola fina, usada em selos e envelopes, ao óleo comes...', '<!-- wp:paragraph -->
<p>O milho para além de ser alimento precioso, dele obtém-se muitos produtos, desde a cola fina, usada em selos e envelopes, ao óleo comestível.</p>
<!-- /wp:paragraph -->

<!-- ...', 'Curiosidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-02-09 14:44:28+00', 323, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'tenis-papel-e-pneu-conheca-oito-produtos-feitos-de-milho', true), ('677d47fd-3f62-4480-861b-006c81ab185b', 'Projectos de mitigação de salinidade do solo beneficiam produtores de Moamba e KaMavota', '
Estão em curso projectos de combate á salinidade do solo nos distritos de Boane e KaMavota, implementados pela ABIODES, CMCM, FAEFUEM, ...', '<!-- wp:paragraph -->
<p>Estão em curso projectos de combate á salinidade do solo nos distritos de Boane e KaMavota, implementados pela ABIODES, CMCM, FAEFUEM, na província de Maputo.</p>
<!-- /wp:par...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-11-20 04:15:07+00', 351, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'salinidade-do-solo', true), ('6b6b76f9-0617-4879-893c-f6dff044d015', 'PROMER: catalisador da produção agrícola', '
O Ministério da Terra, Ambiente e Desenvolvimento Rural (MITADR) implementa, através da Direcção Nacional do Desenvolvimento Rural (DND...', '<!-- wp:paragraph -->
<p>O Ministério da Terra, Ambiente e Desenvolvimento Rural (MITADR) implementa, através da Direcção Nacional do Desenvolvimento Rural (DNDR), o programa de Promoção dos Mercados ...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-07 20:26:57+00', 246, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'promer-catalisador-da-producao-agricola', true), ('6fe83b56-8b2f-4105-8e38-4b7b5ed49f17', '“Somos reféns da EDM”– Moradores de Magoanine "A"', '
Os moradores do bairro de Magoanine “A”, nos arredores da cidade de Maputo, passam noites às escuras quase todos os dias, das 17 às 6h ...', '<!-- wp:paragraph -->
<p>Os moradores do bairro de Magoanine “A”, nos arredores da cidade de Maputo, passam noites às escuras quase todos os dias, das 17 às 6h do dia seguinte, segundo informações for...', 'Comunidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-06-06 20:55:50+00', 179, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'moradores-de-magoanine-a-somos-refens-da-edm', true), ('71fe8739-6285-4fb8-96df-cc482da52438', 'Assoreamento da vala do rio Mulaúze agudiza fraca produção agrícola', '
Os danos causados pelas actuais enxurradas agravam a fraca produtividade e produção agrícola nas bermas do rio Mulaúze, na cidade de Ma...', '<!-- wp:paragraph -->
<p>Os danos causados pelas actuais enxurradas agravam a fraca produtividade e produção agrícola nas bermas do rio Mulaúze, na cidade de Maputo</p>
<!-- /wp:paragraph -->

<!-- wp...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-30 20:19:01+00', 377, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'assoreamento-do-rio-mulauze-agudiza-fraca-producao-agricola', true), ('733abe43-ed36-4522-8746-76aaf215ca23', 'Feijão Bóer moçambicano retido na Índia', '
Estão retidos cerca de 30 mil toneladas de Feijão Bóer e Soja em Mubai, na Índia, resultado da disputa empresarial envolvendo duas empr...', '<!-- wp:paragraph -->
<p>Estão retidos cerca de 30 mil toneladas de Feijão Bóer e Soja em Mubai, na Índia, resultado da disputa empresarial envolvendo duas empresas nacionais, todas sediadas em Nampul...', 'Agro-negocio', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2022-11-04 13:56:48+00', 458, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'feijao-boer', true), ('77a689e5-4ae8-4983-bc6e-a37d43a4afd4', 'Agronegócio: Standard Bank promove comercialização e exportação de produtos agrícolas', '
O Standard Bank realizou, na passada quarta-feira (3), na cidade da Beira, província de Sofala, um fórum de Agronegócio com objetivo de...', '<!-- wp:paragraph -->
<p>O Standard Bank realizou, na passada quarta-feira (3), na cidade da Beira, província de Sofala, um fórum de Agronegócio com objetivo de dinamizar a cadeia de valor agrária, a ...', 'Agro-negocio', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2022-11-05 13:08:11+00', 306, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'standar-bank-e-promocao-de-agronegocio', true), ('781777e6-2276-44e1-a441-542dcf238a40', 'ZONAS BAIXAS: propícias para boa produção agrícola', '
Cultivar nas zonas baixas pode ser solução para a boa produção agrícola, como forma de aproveitar a humidade residual e privilegiar o u...', '<!-- wp:paragraph -->
<p>Cultivar nas zonas baixas pode ser solução para a boa produção agrícola, como forma de aproveitar a humidade residual e privilegiar o uso de sementes de ciclo curto, perante u...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-06-05 19:27:57+00', 330, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'zonas-baixas-propicias-para-boa-producao-agricola', true), ('79ea816a-b250-44f4-9335-d45661cf0f0f', 'Em Maputo: ausência de matadouro condiciona venda de carne de coelho', '
A falta de uma casa de matança, nas cidades de Maputo e Matola, está a condicionar a venda de carne de coelho na província de Maputo.</...', '<!-- wp:paragraph -->
<p>A falta de uma casa de matança, nas cidades de Maputo e Matola, está a condicionar a venda de carne de coelho na província de Maputo.</p>
<!-- /wp:paragraph -->

<!-- wp:parag...', 'Agro-pecuaria', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-05-10 13:15:24+00', 186, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'em-maputo-ausencia-de-matadouro-condiciona-venda-de-carne-de-coelho', true), ('809aa00a-4425-4fe9-9036-17dfa11cc7ca', 'MADER e USAID unidos para fortalecer sistema de mercado agrícola', '
O Inspector-Geral do Ministério da Agricultura e Desenvolvimento Rural (MADER), Rui Mapatsa, anunciou na sexta-feira, 19 de Abri...', '<p><!-- wp:paragraph --></p>
<p>O Inspector-Geral do Ministério da Agricultura e Desenvolvimento Rural (MADER), Rui Mapatsa, anunciou na sexta-feira, 19 de Abril, que o Governo está a trabalhar em con...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2024-04-23 09:50:32+00', 174, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'mader-e-usaid-unidos-para-fortalecer-sistema-de-mercado-agricola', true), ('84a42300-7d4b-4240-b6be-7eaa860686a5', 'Inadimplência ameaça continuidade do fornecimento de água em Moçambique', 'A sustentabilidade financeira dos operadores privados de abastecimento de água em Moçambique está sob séria ameaça. Os níveis de cobrança continuam baixos — ...', '<p>A sustentabilidade financeira dos operadores privados de abastecimento de água em Moçambique está sob séria ameaça. Os níveis de cobrança continuam baixos — abaixo dos 40% — comprometendo a continu...', 'Comunidade', 'https://ppgmtxzuaxqshipnvebl.supabase.co/storage/v1/object/public/news-images/Aguas.jpg', '2025-07-24 09:39:59+00', 512, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'inadimplencia-ameaca-continuidade-do-fornecimento-privado-de-agua-em-mocambique', true), ('8ca61112-b642-4637-b92c-964df34457f0', 'Africa do Sul e Moçambique: Formalizam entendimento para incrementar produção agrícola', '
A Federação Nacional de Associações Agrárias de Moçambique (FENAGRI) e Representantes da União Nacional dos Farmeiros da província de M...', '<!-- wp:paragraph -->
<p>A Federação Nacional de Associações Agrárias de Moçambique (FENAGRI) e Representantes da União Nacional dos Farmeiros da província de Mpumalanga, (NAFU) assinaram, recentement...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-16 20:26:10+00', 178, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'africa-do-sul-e-mocambique-formalizam-entendimento-para-incrementar-producao-agricola', true), ('9902b433-bb94-4d3f-b39d-660aa7ae038e', 'Conheça as potencialidades do Alho', '
O alho é usado medicinalmente há mais de 5 mil anos, e era conhecido pelos gregos como "rosa de mau cheiro".
...', '<!-- wp:paragraph -->
<p>O alho é usado medicinalmente há mais de 5 mil anos, e era conhecido pelos gregos como "rosa de mau cheiro".</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Para retirar ...', 'Curiosidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-06-06 07:17:34+00', 243, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'conheca-as-potencialidades-do-alho', true), ('9e5de66f-617d-42c6-bf7c-60395bc6a196', 'Afinal, o que está a acontecer no sector agrário moçambicano?', '
O discurso sobre as acções de desenvolvimento do sector agrícola, em Moçambique, tem sido uma das principais agendas dos media. Trata s...', '<!-- wp:paragraph -->
<p>O discurso sobre as acções de desenvolvimento do sector agrícola, em Moçambique, tem sido uma das principais agendas dos media. Trata se de uma temática que divide a opinião p...', 'Sector agrario', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-04-10 06:56:34+00', 530, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'afinal-o-que-esta-a-acontecer-no-sector-agrario-mocambicano', true), ('a245061f-64ae-4993-b48b-07a7d17333a2', 'Desafio do Desenvolvimento da Agricultura em Moçambique', '
Moçambique, com a sua rica base de recursos naturais e terras férteis, tem um potencial imenso para se tornar um destaque na produção a...', '<!-- wp:paragraph -->
<p>Moçambique, com a sua rica base de recursos naturais e terras férteis, tem um potencial imenso para se tornar um destaque na produção agrícola a nível global. No entanto, o le...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-10-05 22:11:02+00', 410, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'desafio-do-desenvolvimento-da-agricultura-em-mocambique', true), ('a6c93f26-68fe-43bb-9fdf-2aa5e27943a2', 'Aranhas produzem leite mais nutritivo que leite de vaca, diz estudo', '
De vacas a cabras, uma variedade de animais é conhecida por produzir leite para alimentar seus filhotes. Agora, um novo estudo sugere q...', '<!-- wp:paragraph -->
<p>De vacas a cabras, uma variedade de animais é conhecida por produzir leite para alimentar seus filhotes. Agora, um novo estudo sugere que as aranhas também podem produzir flui...', 'Curiosidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-04-11 14:08:00+00', 351, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'aranhas-produzem-leite-mais-nutritivo-que-leite-de-vaca-diz-estudo', true), ('a9457c3b-7380-4e00-9c6a-a75182770321', 'Em Marracuene: Agricultores afectados pelas inundações recebem kits de apoio', '
Os beneficiários do Programa de Desenvolvimento Inclusivo de Cadeias de Valores Agro-alimentares (PROCAVA) de Marracuene receberam, na ...', '<!-- wp:paragraph -->
<p>Os beneficiários do Programa de Desenvolvimento Inclusivo de Cadeias de Valores Agro-alimentares (PROCAVA) de Marracuene receberam, na segunda-feira (17), insumos para recuper...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-04-19 21:20:06+00', 348, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'em-marracuene-agricultores-afectados-pelas-inundacoes-recebem-kits-de-apoio', true), ('ada50bf4-8b34-4cc4-854c-0350ddccd7bf', 'Ajuda humanitária da covid-19 resulta em morte do chefe de quarteirão', '
O valor disponibilizado pelo Governo de Moçambique para mitigar os efeitos da COVID-19 às famílias necessitadas culminou, no dia 5 de m...', '<!-- wp:paragraph -->
<p>O valor disponibilizado pelo Governo de Moçambique para mitigar os efeitos da COVID-19 às famílias necessitadas culminou, no dia 5 de março do ano em curso, na morte de Isaque...', 'Comunidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-07 20:53:22+00', 479, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'ajuda-humanitaria-da-covid-19-resulta-em-morte-do-chefe-de-quarteirao-nove', true), ('ae320050-c490-49cc-86ab-f9391a6083dc', 'Investimentos em tecnologia agrícola e práticas sustentáveis ​​impulsionam a produtividade no país', 'Moçambique tem experimentado um crescimento significativo na produção de milho e arroz em 2025, com uma previsão de aumento de 15% na produção total, em comparação com o ano anterior', '<p><strong>Moçambique tem experimentado um crescimento significativo na produção de milho e arroz em 2025, com uma previsão de aumento de 15% na produção total, em comparação com o ano anterior.</stro...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2025-01-27 15:31:30+00', 502, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'investimentos-em-tecnologia-agricola-e-praticas-sustentaveis-impulsionam-a-produtividade-no-pais', true), ('ae805af7-dbda-4b69-a43f-68d92e3359fc', 'Tongaat Hulett com capacidade para abastecer mercado interno', '
A Tongaat Hulett confirma ter capacidade para a produção de açúcar suficiente para abastecer os mercados interno e externo, apesar dos ...', '<!-- wp:paragraph -->
<p>A Tongaat Hulett confirma ter capacidade para a produção de açúcar suficiente para abastecer os mercados interno e externo, apesar dos impactos do ciclone Freddy.</p>
<!-- /wp...', 'Agro-negocio', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-04-11 14:30:03+00', 489, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'tongaat-hulett-com-capacidade-para-abastecer-mercado-interno', true), ('b0175785-0e70-43f7-91de-e6e804f93ab2', 'Em Gaza: Projecto do desenvolvimento comunitário beneficia vendedores de fruta', '
·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Frutos silvestres: matéria-...', '<!-- wp:paragraph {"canvasClassName":"cnvs-block-core-paragraph-1684698535791"} -->
<p><strong>·&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Frutos silvestres: matéria-prima para produção de licores e polpas ...', 'Fruticultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2022-09-29 17:59:22+00', 529, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'em-gaza-projecto-do-desenvolvimento-comunitario-beneficia-vendedores-de-fruta', true), ('b06a96ec-05f5-40c7-ad87-c7ed78a7d794', 'Criado Conselho Nacional de Apicultura', '
Foi criado, recentemente, o Conselho Nacional de Apicultura de Moçambique (ACNAM), com vista a Promover o desenvolvimento do sector apí...', '<!-- wp:paragraph -->
<p>Foi criado, recentemente, o Conselho Nacional de Apicultura de Moçambique (ACNAM), com vista a Promover o desenvolvimento do sector apícola robusto, progressivo, inclusivo e s...', 'Apicultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-05-29 14:07:26+00', 169, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'criado-conselho-nacional-de-apicultura', true), ('b5e6fd11-6ff8-40f2-8cb8-e4d107ba0fcc', 'Ciclone Fredy: BNI desembolsa 75 milhões de meticais para apoio às PME´s afectadas', '
O Banco Nacional de Investimento (BNI) vai desembolsar 75 milhões de meticais para o financiamento, especialmente, concebido para apoia...', '<!-- wp:paragraph -->
<p>O Banco Nacional de Investimento (BNI) vai desembolsar 75 milhões de meticais para o financiamento, especialmente, concebido para apoiar as pequenas e médias empresas baseadas...', 'Agro-negocio', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-04-15 09:43:41+00', 160, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'ciclone-fredy-bni-desembolsa-75-milhoes-de-meticais-para-apoio-aos-agricultores-afectados', true), ('b79e2dc8-066a-4e34-983d-b84cc3fc1e1f', 'Está em curso plano integrado de empoderamento do sector privado', '
Está em curso um plano estratégico de empoderamento do sector privado, com vista a potencializar a comercialização de produtos agrícola...', '<!-- wp:paragraph -->
<p>Está em curso um plano estratégico de empoderamento do sector privado, com vista a potencializar a comercialização de produtos agrícolas no país.&nbsp;</p>
<!-- /wp:paragraph ...', 'Agro-negocio', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-04-15 09:53:56+00', 316, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'esta-em-curso-plano-integrado-de-empoderamento-do-sector-privado', true), ('b887dbad-57b1-41db-a83c-8fc05513e9e1', 'Fome no guava: "sem água não há comida"- Jaime Agostinho', '
A falta de água contribui para a fraca produção agrícola e coloca as famílias cuja base de subsistência é a agricultura expostos à fome...', '<!-- wp:paragraph -->
<p>A falta de água contribui para a fraca produção agrícola e coloca as famílias cuja base de subsistência é a agricultura expostos à fome. Este é o cenário vivido pelos campones...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-07-06 10:23:49+00', 61, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'fome-no-guava-sem-agua-nao-ha-comida-jaime-agostinho', true), ('bcfda020-ee7f-40d9-983c-86f8ce64709f', 'Governo lança projecto de reabilitação da estrada nacional número um', '
A Administração Nacional de Estradas (ANE) iniciou a preparação do projecto de reabilitação da Estrada Nacional Número 1 (EN1),...', '<!-- wp:paragraph -->
<p><strong>A Administração Nacional de Estradas (ANE) iniciou a preparação do projecto de reabilitação da Estrada Nacional Número 1 (EN1), com apoio de consultores internacionais...', 'Comunidade', '<![CDATA[https://entrecampos.co.mz/wp-content/uploads/2025/06/Infara-estrutars.jpg]]>', '2025-06-27 14:09:25+00', 502, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'governo-lanca-projecto-de-reabilitacao-da-estrada-nacional-numero-um', true), ('c0476be5-64b7-4e92-a728-2255e806659e', 'Conheça os benefícios da papaia para cabelos e pele', 'A beleza e a saúde da pele, cabelos e unhas está diretamente ligada a uma alimentação rica em vitaminas e minerais', '<!-- wp:paragraph -->
<p>A beleza e a saúde da pele, cabelos e unhas está diretamente ligada a uma alimentação rica em vitaminas e minerais</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Colocar...', 'Curiosidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-16 20:43:50+00', 172, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'conheca-os-beneficios-da-papaia-para-cabelos-e-pele', true), ('c1110782-4a16-44fa-a8ed-4f181e4ec84e', 'Há disputa de cabeças de Gado Bovino entre Maputo e Manhiça', '
A dificuldade de transporte de animais à província de Maputo, devido às cheias que assolam a região sul do país, cria disputa de Gado B...', '<!-- wp:paragraph -->
<p>A dificuldade de transporte de animais à província de Maputo, devido às cheias que assolam a região sul do país, cria disputa de Gado Bovino no mercado de carnes vermelhas da ...', 'Agro-negocio', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-16 20:11:40+00', 199, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'mercado-das-carnes-vermelhas', true), ('c20981da-f14e-4e9a-a88d-45435398b1eb', 'Iniciativa do Bill Gates: Produção de 30 Milhões de Mosquitos por Semana', '
Bill Gates, além de liderar a Microsoft, é um visionário que se tornou um dos maiores proprietários de terras agrícolas nos EUA, com ma...', '<!-- wp:paragraph -->
<p>Bill Gates, além de liderar a Microsoft, é um visionário que se tornou um dos maiores proprietários de terras agrícolas nos EUA, com mais de 109 mil hectares, e possui uma faz...', 'Você-sabiaA?', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-12-17 15:40:04+00', 414, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'iniciativa-do-bill-gates-producao-de-30-milhoes-de-mosquitos-por-semana', true), ('c44f93ee-3aa7-4f37-9eae-985d88411cb6', 'Alho como biopesticida para protecção de plantas', 'Não faz apenas bem à saúde humana. As potencialidades deste alimento no combate de pragas e doenças são maiores do que aquelas, à partida, poderia julgar. Descubra quais são as melhores formas de o utilizar no jardim.', '<p><!-- wp:paragraph --></p>
<p><strong>Não faz apenas bem à saúde humana. As potencialidades deste alimento no combate de pragas e doenças são maiores do que aquelas, à partida, poderia julgar. Descu...', 'Curiosidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-06-06 07:08:24+00', 409, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'alho-como-biopesticida-para-proteccao-de-plantas', true), ('ca02803e-7f68-41bd-9e13-0d613757b1e3', 'Moçambique e Zimbábwe lançam projecto transfronteiriço de 3,1 milhões', 'Moçambique e o Zimbábwe vão investir cerca de 3,1 milhões de dólares, equivalentes a 200 milhões de meticais, num projecto conjunto que visa impulsionar cade...', '<p>Moçambique e o Zimbábwe vão investir cerca de 3,1 milhões de dólares, equivalentes a 200 milhões de meticais, num projecto conjunto que visa impulsionar cadeias de valor agrícola e o comércio trans...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2025-07-04 06:21:26+00', 313, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'mocambique-e-zimbabwe-lancam-projecto-transfronteirico-de-31-milhoes', true), ('cd5964cc-f240-44e7-9b43-037f4ff5773e', 'Agricultura como resposta contra o impacto da COVID-19', '
Incomáti Parque introduz, na grelha das suas actividades, a prática de actividades agrícolas por forma a colmatar o impacto económico s...', '<!-- wp:paragraph -->
<p>Incomáti Parque introduz, na grelha das suas actividades, a prática de actividades agrícolas por forma a colmatar o impacto económico social causado pela pandeia da COVID-19 a...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2021-06-09 15:32:57+00', 480, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'agricultura-como-resposta-contra-o-impacto-da-covid-19-2', true), ('d4e21a56-d129-41bc-8b1f-8056087c230c', 'Escassez de produtos aumenta valor de compra no mercado grossista do Zimpeto', '
A batata, Tomate e Cebola, principalmente produzidos em grandes quantidades no sul do país, &nbsp;a sua escassez altera o valor de comp...', '<!-- wp:paragraph -->
<p>A batata, Tomate e Cebola, principalmente produzidos em grandes quantidades no sul do país, &nbsp;a sua escassez altera o valor de compra no mercado grossista do Zimpeto, cida...', 'Agro-negocio', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-23 21:17:14+00', 197, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'escassez-de-produtos-aumenta-valor-de-compra-no-mercado-grossista-do-zimpeto', true), ('dbbdc482-1556-450f-8f32-7eeec03dbedc', 'Moçambique e Banco Mundial apostam em agricultura sustentável para impulsionar economia nacional', 'O Governo de Moçambique e o Banco Mundial estão a definir uma nova etapa de cooperação centrada na produção alimentar, industrialização florestal e sustentab...', '<p>O Governo de Moçambique e o Banco Mundial estão a definir uma nova etapa de cooperação centrada na produção alimentar, industrialização florestal e sustentabilidade ambiental. A meta é transformar ...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2025-07-15 14:47:09+00', 381, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'mocambique-e-banco-mundial-apostam-em-agricultura-sustentavel-para-impulsionar-economia-nacional', true), ('e3fb45bb-5531-4957-96ac-b7933dbbeb01', 'Agência do Zambeze Investe U$D 7,9 Milhões em Projectos de Inovação Agrícola', '
A Agência de Desenvolvimento do Vale do Zambeze (ADZ) alocou 7,9 milhões de dólares para impulsionar projectos agrários inovador...', '<p><!-- wp:paragraph --></p>
<p>A Agência de Desenvolvimento do Vale do Zambeze (ADZ) alocou 7,9 milhões de dólares para impulsionar projectos agrários inovadores, na região central de Moçambique.</p>...', 'Comunidade', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2024-04-19 15:59:36+00', 275, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'agencia-do-zambeze-investe-ud-79-milhoes-em-projectos-de-inovacao-agricola', true), ('e625d444-a633-40a5-b5dc-b7ea6d58dd62', 'Exportação de produtos agrícolas: Moçambique arrecada USD92 milhões', '
O Presidente da República (PR), Filipe Jacinto Nyusi, afirmou, recentemente, que o país arrecadou mais de noventa e dois milhões de dól...', '<!-- wp:paragraph -->
<p>O Presidente da República (PR), Filipe Jacinto Nyusi, afirmou, recentemente, que o país arrecadou mais de noventa e dois milhões de dólares, fruto da exportação de produtos ag...', 'Agro-negocio', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-04-15 10:12:29+00', 242, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'exportacao-de-produtos-agricolas-mocambique-alcanca-usd92', true), ('e772bbe2-1628-4875-8687-283cf07cea5f', 'EM NAMPULA: aumento da produção de Algodão  estimula construção de armazéns', '
O aumento da produção de Algodão, na campanha agrícola 21|22, estimulou a construção de mais 3 armazéns, dos 5 já existentes, na Socied...', '<!-- wp:paragraph -->
<p>O aumento da produção de Algodão, na campanha agrícola 21|22, estimulou a construção de mais 3 armazéns, dos 5 já existentes, na Sociedade Algodoeira de Mutuali, no distrito d...', 'Sector agrario', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2022-08-25 21:51:28+00', 169, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'em-nampula-aumento-da-campanha-agricola-estimula-construcao-de-armazens', true), ('e7a205e1-9306-41bd-9ad5-b4a3461d2ba8', 'Fábrica da Huawei em Moçambique pode impulsionar desenvolvimento rural', '
A multinacional Huawei estuda, em articulação com o Governo moçambicano, a possibilidade de erguer uma unidade fabril de telemóveis no ...', '<!-- wp:paragraph -->
<p>A multinacional Huawei estuda, em articulação com o Governo moçambicano, a possibilidade de erguer uma unidade fabril de telemóveis no país, vocacionada para responder às exig...', 'Comunidade', '<![CDATA[https://entrecampos.co.mz/wp-content/uploads/2025/06/Huawei-Estuda-Construcao-de-Fabrica-de-Telemoveis-em-Mocambique-com-Foco-nas-Zonas-Rurais.jpg]]>', '2025-06-27 14:40:33+00', 71, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'fabrica-da-huawei-em-mocambique-pode-impulsionar-desenvolvimento-rural', true), ('ea7203bd-0722-4bc6-9ff3-3cf827564e61', 'Women In Business (WIN), Procava e SPEED colaboram na revisão da estratégia de género do MADER', '
Em uma iniciativa conjunta entre o programa Women In Business (WIN), a Procava e o programa de apoio das Organizações da Sociedade Civi...', '<!-- wp:paragraph -->
<p>Em uma iniciativa conjunta entre o programa Women In Business (WIN), a Procava e o programa de apoio das Organizações da Sociedade Civil que promovem a transparência e a respo...', 'Oportunidades', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2024-02-23 07:52:57+00', 481, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'women-in-business-win-procava-e-speed-colaboram-na-revisao-da-estrategia-de-genero-do-mader', true), ('f1a03414-4357-4913-8d19-bcfe75df58bd', 'Desembolsado US$ 19 milhões para reduzir impacto das mudanças climáticas no país', '
O Governo da Suécia disponibilizou, recentemente, US$ 19 milhões com vista a financiar o Programa de Financiamento Climático aos Govern...', '<!-- wp:paragraph -->
<p>O Governo da Suécia disponibilizou, recentemente, US$ 19 milhões com vista a financiar o Programa de Financiamento Climático aos Governos Locais (LOCAL) no país.</p>
<!-- /wp:...', 'Ambiente', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-07 21:14:07+00', 146, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'desembolsado-us-19-milhoes-para-reduzir-impacto-das-mudancas-climaticas-no-pais', true), ('f252cec0-139f-4ac0-8519-0cff46170fbd', 'Lançado concurso para financiamento de projectos agrícolas sob programa "Feed the future RESINA"', '
Foi lançado recentemente, na província de Nampula, o concurso para financiamento de projectos agrícolas sob of Projecto Feed the</e...', '<!-- wp:paragraph -->
<p>Foi lançado recentemente, na província de Nampula, o concurso para financiamento de projectos agrícolas sob of Projecto <em>Feed the</em> <em>Future Mozambique</em> Resiliênci...', 'Oportunidades', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-30 20:24:06+00', 174, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'lancado-concurso-para-implementacao-de-projectos-resina-e-premier', true), ('f286afe7-bdb3-4075-a7e1-babe241f9954', 'Políticas agrárias como desafio dos avanços do sector', '
O desenvolvimento do sector agrário está estagnado devido às obsoletas políticas que constituem o principal desafio do sector – disse T...', '<!-- wp:paragraph -->
<p>O desenvolvimento do sector agrário está estagnado devido às obsoletas políticas que constituem o principal desafio do sector – disse Tatiana Mata, numa entrevista concebida p...', 'Entrevsta', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-30 21:25:01+00', 535, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'politicas-agrarias-como-desafio-dos-avancos-do-sector', true), ('f6307dd9-fb3b-4b1f-a713-05874362ec12', 'Agricultores protestam pagamento de cotas sem retorno', '
O pagamento de cotas anuais sem retorno á União das Associações dos Agricultores (UAA), inquieta associações do Vale do Infulene, na ci...', '<!-- wp:paragraph -->
<p>O pagamento de cotas anuais sem retorno á União das Associações dos Agricultores (UAA), inquieta associações do Vale do Infulene, na cidade de Maputo.</p>
<!-- /wp:paragraph -...', 'Sector agrario', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2023-03-16 19:59:00+00', 143, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'agricultura-familiar', true), ('f972cd8c-53fb-462a-889e-d2f225f0d2b1', 'Custo de substrato reduz nível de produção de mudas', '
Os actores que operam no sector agrário, especialmente na produção e comercialização de substratos, relatam subidas de preços de adubos...', '<!-- wp:paragraph -->
<p>Os actores que operam no sector agrário, especialmente na produção e comercialização de substratos, relatam subidas de preços de adubos que, consequentemente, reduz o nível de...', 'Agro-negocio', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2022-11-04 20:40:20+00', 263, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'producao-de-mudas', true), ('fbdb0dba-e4f3-4dba-bcf3-882f39929143', 'TÉCNICAS AGRÍCOLAS: de obstáculo a oportunidade', '
Enquanto uns reclamam das barreiras, outros transformam-nas em oportunidades.


<!-- wp:par...', '<!-- wp:list -->
<ul><li><strong>Enquanto uns reclamam das barreiras, outros transformam-nas em oportunidades.</strong></li></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>O desassoreamento da vala ...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2022-08-03 19:54:31+00', 236, '2026-04-24 11:23:51.241139+00', 'baseagrodata', 'tecnicas-agricolas-de-obstaculo-a-oportunidade', true), ('fc27fba1-eeaf-4a18-ac86-637e8a151238', 'Moçambique projecta criação de oito centros de processamento agrícola', '
Moçambique projecta a criação de oito novos centros de processamento de produtos agrícolas em várias regiões do país. Uma inicia...', '<p><!-- wp:paragraph --></p>
<p>Moçambique projecta a criação de oito novos centros de processamento de produtos agrícolas em várias regiões do país. Uma iniciativa que constitui parte da primeira fas...', 'Agro-processamento', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2024-06-14 21:08:07+00', 251, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'mocambique-projecta-criacao-de-oito-centros-de-processamento-agricola', true), ('fd963160-2b8c-4970-9461-3924f17f10fd', 'Seguro agrícola passa a integrar política de resiliência climática', 'O Governo moçambicano pretende avançar com a padronização do sistema de seguro agrário como mecanismo de mitigação dos impactos das alterações climáticas e p...', '<p>O Governo moçambicano pretende avançar com a padronização do sistema de seguro agrário como mecanismo de mitigação dos impactos das alterações climáticas e promoção da resiliência dos produtores ag...', 'Agricultura', 'https://entrecampos.co.mz/wp-content/uploads/2021/06/CAMPANHAAGRICOLA.jpg', '2025-06-30 08:19:02+00', 336, '2026-04-24 11:23:52.853064+00', 'baseagrodata', 'seguro-agricola-passa-a-integrar-politica-de-resiliencia-climatica', true);